bump min cabal-version and extra common stanza
Hackage is now rejecting packages with cabal-version lower bound
less than 1.10:

`cabal upload` output:

  Uploading /usr/home/fraser/dev/hs-jose/dist-newstyle/sdist/jose-0.8.3.tar.gz...
  Error uploading /usr/home/fraser/dev/hs-jose/dist-newstyle/sdist/jose-0.8.3.tar.gz: http code 400
  Error: Invalid package

  'cabal-version' must be at least 1.10

Bump the lower bound.  Cabal v1.10 also requires adding the
`default-language' field to each component.  So put the lower bound
at cabal v2.2 and extract "common stanzas"[1] to reduce duplication.

[1] https://vrom911.github.io/blog/common-stanzas